# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


  Course.create!(course_name: 'Introduction to Computer Programming', course_code: 'CSC108',course_prof: 'J Smith',description:'Programming in a language such as Python. Elementary data types, lists, maps.  Program structure: control flow, functions, classes, objects, methods. Algorithms and problem solving. Searching, sorting, and complexity. Unit testing. No prior programming experience required.NOTE: You may not take this course concurrently with CSC120H1/CSC148H1, but you may take CSC148H1 after CSC108H1.', prerequisites: 'none')
  Course.create!(course_name: 'Introduction to the Theory of Computation', course_code: 'CSC236',course_prof: 'S Sharmin', description:'Mathematical induction; correctness proofs for iterative and recursive algorithms; recurrence equations and their solutions (including the \"Master Theorem\"); introduction to automata and formal languages.', prerequisites:'CSC148H5' )
  Course.create!(course_name: 'Business Process Engineering', course_code: 'MIE 333',course_prof: 'Mariano Consens', description:'Covers financial analysis of firms in the financial services industries: accounting and disclosure rules for financial instruments. Gives an in-depth understanding of how financial reports provide fairly accurate information about the risks and performance of banks and other financial services firms. Not eligible for CR/NCR option. Contact Rotman Commerce for details.', prerequisites:'none' )
  Course.create!(course_name: 'Data Modelling', course_code: 'MIE 511',course_prof: 'Mariano Consens', description:'Covers financial analysis of firms in the financial services industries: accounting and disclosure rules for financial instruments. Gives an in-depth understanding of how financial reports provide fairly accurate information about the risks and performance of banks and other financial services firms. Not eligible for CR/NCR option. Contact Rotman Commerce for details.', prerequisites:'none' )
  Course.create!(course_name: 'Operations Research', course_code: 'MIE 355',course_prof: 'Dionne Aleman', description:'Covers financial analysis of firms in the financial services industries: accounting and disclosure rules for financial instruments. Gives an in-depth understanding of how financial reports provide fairly accurate information about the risks and performance of banks and other financial services firms. Not eligible for CR/NCR option. Contact Rotman Commerce for details.', prerequisites:'none' )
  Course.create!(course_name: 'Financial Enginering', course_code: 'MIE 521',course_prof: 'Kwong Chang', description:'Covers financial analysis of firms in the financial services industries: accounting and disclosure rules for financial instruments. Gives an in-depth understanding of how financial reports provide fairly accurate information about the risks and performance of banks and other financial services firms. Not eligible for CR/NCR option. Contact Rotman Commerce for details.', prerequisites:'none' )
